add_library(msodbcsql INTERFACE IMPORTED)

set_target_properties(msodbcsql PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include"
    INTERFACE_LINK_DIRECTORIES "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib"
    INTERFACE_LINK_LIBRARIES "msodbcsql18"
)
